[tool.ruff]
ignore = ["F401"]

[tool.ruff.lint]

ignore = ["F401", "D104", "D212", "D213"]
select = ["E", "F", "B", "D"]

# Specific file ignores 
per-file-ignores = {
    "__init__.py" = ["F401"],
    "migrations/*.py" = ["E501", "F401"]
}