name: Development Checking

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - devs

jobs:
  development:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Node.js properly
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Front-End Dependencies
      run: npm install
      working-directory: ./frontend

    - name: Run ESLint on Front-End
      run: npm run lint -- --max-warnings=0
      working-directory: ./frontend

    - name: Build the Front-End
      run: npm run build
      working-directory: ./frontend

    - name: Install Back-End Dependencies
      run: pip install -r ./backend/requirements.txt ruff isort pytest-django coverage

    - name: Run Python Linter
      run: |
        ruff format ./backend/server 
        isort ./backend/server  
        ruff check ./backend/server 

    - name: Run Back-End Tests with Coverage
      run: |
        coverage run -m pytest
        coverage report
